# Generated by Django 4.1.7 on 2023-04-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login_system", "0006_remove_passwordresettoken_expired_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="OTP"
            ),
        ),
    ]
