# Generated by Django 4.1.7 on 2023-05-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login_system", "0007_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
