# Generated by Django 4.1.7 on 2023-05-17 10:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateField(
                        default=datetime.datetime(
                            2023,
                            5,
                            17,
                            10,
                            30,
                            52,
                            529846,
                            tzinfo=datetime.timezone.utc,
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date(1900, 1, 1)
                            ),
                            django.core.validators.MaxValueValidator(
                                datetime.date(2100, 1, 1)
                            ),
                        ],
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "symptoms",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Symptoms"
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Diagnosis"
                    ),
                ),
                (
                    "medication",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Medication"
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Treatment"
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="PatientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "lastName",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "dateofbirth",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date(1900, 1, 1)
                            ),
                            django.core.validators.MaxValueValidator(
                                datetime.datetime(
                                    2023,
                                    5,
                                    17,
                                    10,
                                    30,
                                    52,
                                    528855,
                                    tzinfo=datetime.timezone.utc,
                                )
                            ),
                        ],
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images", verbose_name="Image")),
                (
                    "cam",
                    models.ImageField(
                        null=True, upload_to="images", verbose_name="Image"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Image Title")),
                (
                    "result",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Evaluation"
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Comments"
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="svmApp.consultationmodel",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="svmApp.patientmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultationmodel",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="svmApp.patientmodel"
            ),
        ),
    ]
